ALTER TABLE equipment ADD COLUMN IF NOT EXISTS manufacturer VARCHAR(255) DEFAULT '';
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS serial_number VARCHAR(100) DEFAULT '';
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS year_of_manufacture INTEGER;
